defaults:
  - submitit_slurm

_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
timeout_min: 5760 # 96 hours
tasks_per_node: 1
nodes: 1
name: ${hydra.job.name}
comment: null
exclude: null
signal_delay_s: 60
max_num_timeout: 0
additional_parameters: {}
setup:
  - export MONGODB_URI="$(printenv MONGODB_URI)"
  - export MONGODB_USER="$(printenv MONGODB_USER)"
  - export MONGODB_PASSWORD="$(printenv MONGODB_PASSWORD)"
  - export MONGODB_HOST="$(printenv MONGODB_HOST)"
  - export MONGODB_DB="$(printenv MONGODB_DB)"
gres: gpu:1
mem_gb: 16
cpus_per_task: 4
partition: gpu_a100